/* Darwin links shared graph code that references unavailable non-Metal GPU hooks. */

#define DS4_METAL_UNAVAILABLE_INT(name) \
    extern "C" int name(...) { return 0; }

DS4_METAL_UNAVAILABLE_INT(ds4_gpu_add_xdev_tensor)
DS4_METAL_UNAVAILABLE_INT(ds4_gpu_indexer_top1_value_tensor)
DS4_METAL_UNAVAILABLE_INT(ds4_gpu_kv_fp8_store_raw_decode_rows_tensor)
DS4_METAL_UNAVAILABLE_INT(ds4_gpu_matmul_q8_0_kslice_hc_expand_add_tensor)
DS4_METAL_UNAVAILABLE_INT(ds4_gpu_rope_tail_decode_rows_tensor)
DS4_METAL_UNAVAILABLE_INT(ds4_gpu_routed_moe_batch_owned_tensor)
DS4_METAL_UNAVAILABLE_INT(ds4_gpu_routed_moe_one_owned_tensor)
DS4_METAL_UNAVAILABLE_INT(ds4_gpu_routed_moe_owned_packed_combine_tensor)
DS4_METAL_UNAVAILABLE_INT(ds4_gpu_routed_moe_owned_slots_combine_rows_tensor)
DS4_METAL_UNAVAILABLE_INT(ds4_gpu_routed_moe_owned_slots_combine_tensor)
DS4_METAL_UNAVAILABLE_INT(ds4_gpu_shared_down_hc_expand_add_q8_0_tensor)
DS4_METAL_UNAVAILABLE_INT(ds4_gpu_shared_down_hc_expand_owned_q8_0_tensor)
DS4_METAL_UNAVAILABLE_INT(ds4_gpu_tensor_wait_xdev_default)

#undef DS4_METAL_UNAVAILABLE_INT
